[project]
name = "dfa-gym"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dfa-samplers>=0.1.0",
    "gymnasium>=1.0.0",
]
